
import java.util.HashSet;
import java.util.Set;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Resul
 */
public class main extends javax.swing.JFrame {
 private int takimsayisi;
  String takimSayisiStr;
  private String[][] takimadlari;
   private DefaultTableModel model;
   private String baslik []={"Takımlar"};
    
   
    public main() {
        initComponents();
        setTitle("Takım Formu");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTakimsayisi = new javax.swing.JTextField();
        btnTakimsayisi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        takimadlaritablo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Takım Sayısı Giriniz:");

        btnTakimsayisi.setText("Takım Sayısı Onayla");
        btnTakimsayisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTakimsayisiActionPerformed(evt);
            }
        });

        takimadlaritablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(takimadlaritablo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTakimsayisi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTakimsayisi)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTakimsayisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTakimsayisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTakimsayisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTakimsayisiActionPerformed
   takimSayisiStr = txtTakimsayisi.getText(); //txtTakimsayisi adlı textfielddaki sayı değerini takım sayisistr ye atıyor.
if (takimSayisiStr.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Lütfen takım sayısını giriniz.", "Hata", JOptionPane.ERROR_MESSAGE);
} else if (!takimSayisiStr.matches("\\d+")) {
    JOptionPane.showMessageDialog(this, "Takım sayısı sadece sayı olmalıdır.", "Hata", JOptionPane.ERROR_MESSAGE);
} else {
    takimsayisi = Integer.parseInt(takimSayisiStr);
    if (takimsayisi > 0) {
        takimadlari = new String[takimsayisi][2];
        int i;
        Set<String> takimAdlariSet = new HashSet<>(); // Daha önce girilen takım adlarını tutmak için bir Set kullanıyoruz
        for (i = 0; i < takimsayisi; ) {
            String takimAdi = JOptionPane.showInputDialog((i + 1) + ". Takım Adı:");
            if (takimAdi == null) {
                break;
            } else if (takimAdi.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Lütfen takım adını giriniz.", "Hata", JOptionPane.ERROR_MESSAGE);
            } else if (!takimAdi.matches("[a-zA-Z]+")) {
                JOptionPane.showMessageDialog(null, "Takım adı sadece harf içermelidir.", "Hata", JOptionPane.ERROR_MESSAGE);
            } else if (takimAdlariSet.contains(takimAdi)) {
                JOptionPane.showMessageDialog(null, "Aynı takım adını tekrar giremezsiniz.", "Hata", JOptionPane.ERROR_MESSAGE);
            } else {
                takimadlari[i][0] = takimAdi;
                takimadlari[i][1] = "Ek bilgi " + (i + 1);
                takimAdlariSet.add(takimAdi); // Girilen takım adını Set'e ekliyoruz
                i++;
            }
        }
        if (i == takimsayisi) {
            JOptionPane.showMessageDialog(null, "Takım bilgileri kaydedildi.");
            jLabel1.setEnabled(false);
            txtTakimsayisi.setEnabled(false);
            btnTakimsayisi.setEnabled(false);

            model = (DefaultTableModel) takimadlaritablo.getModel();
            for (int j = 0; j < takimsayisi; j++) {
                String takimAdi = takimadlari[j][0];
                model.addRow(new String[]{takimAdi});
            }
            dispose();
            Fikstur fikstur = new Fikstur(takimadlari, takimsayisi);
            fikstur.setVisible(true);
            //Mevcut ekranı kapatım takimadlari ve takimsayisi bilgisini fikstur adlı tabloya gönderir ve fikstur ekranını açar
        }
    } else {
        JOptionPane.showMessageDialog(this, "Takım sayısı 0'dan büyük olmalıdır.", "Hata", JOptionPane.ERROR_MESSAGE);//Takım sayısı 0 dan küçükse hata mesajı verir
    }
}
    }//GEN-LAST:event_btnTakimsayisiActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    DefaultTableModel model = new
         DefaultTableModel (takimadlari,baslik);
        takimadlaritablo.setModel(model);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTakimsayisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable takimadlaritablo;
    private javax.swing.JTextField txtTakimsayisi;
    // End of variables declaration//GEN-END:variables
}
